import { TCandidate } from "@/types/collections";

export const dummyCandidates: TCandidate[] = [
  {
    _id: "cand-1",
    name: "Sarah Johnson",
    slug: "sarah-johnson",
    email: "sarah.johnson@example.com",
    avatar: "/avatars/sarah.jpg",
    password: "hashed_password_1",
    phone: "+1-555-0101",
    role: "candidate",
    city: "San Francisco",
    address: "123 Market St, San Francisco, CA 94103",
    skills: ["React", "TypeScript", "Node.js", "GraphQL", "AWS"],
    education: "Bachelor's in Computer Science - Stanford University",
    yearsOfExperience: "5",
    github: "https://github.com/sarahjohnson",
    linkedin: "https://linkedin.com/in/sarahjohnson",
  },
  {
    _id: "cand-2",
    name: "Michael Chen",
    slug: "michael-chen",
    email: "michael.chen@example.com",
    avatar: "/avatars/michael.jpg",
    password: "hashed_password_2",
    phone: "+1-555-0102",
    role: "candidate",
    city: "New York",
    address: "456 Broadway, New York, NY 10013",
    skills: ["Python", "Django", "PostgreSQL", "Docker", "Kubernetes"],
    education: "Master's in Software Engineering - MIT",
    yearsOfExperience: "7",
    github: "https://github.com/michaelchen",
    linkedin: "https://linkedin.com/in/michaelchen",
  },
  {
    _id: "cand-3",
    name: "Emily Rodriguez",
    slug: "emily-rodriguez",
    email: "emily.rodriguez@example.com",
    avatar: "/avatars/emily.jpg",
    password: "hashed_password_3",
    phone: "+1-555-0103",
    role: "candidate",
    city: "Austin",
    address: "789 Congress Ave, Austin, TX 78701",
    skills: [
      "Figma",
      "UI/UX Design",
      "Prototyping",
      "User Research",
      "Design Systems",
    ],
    education: "Bachelor's in Design - Parsons School of Design",
    yearsOfExperience: "4",
    linkedin: "https://linkedin.com/in/emilyrodriguez",
  },
  {
    _id: "cand-4",
    name: "David Kim",
    slug: "david-kim",
    email: "david.kim@example.com",
    avatar: "/avatars/david.jpg",
    password: "hashed_password_4",
    phone: "+1-555-0104",
    role: "candidate",
    city: "Seattle",
    address: "101 Pine St, Seattle, WA 98101",
    skills: ["DevOps", "CI/CD", "Terraform", "Jenkins", "AWS", "Azure"],
    education:
      "Bachelor's in Information Technology - University of Washington",
    yearsOfExperience: "6",
    github: "https://github.com/davidkim",
    linkedin: "https://linkedin.com/in/davidkim",
  },
  {
    _id: "cand-5",
    name: "Amanda Watson",
    slug: "amanda-watson",
    email: "amanda.watson@example.com",
    avatar: "/avatars/amanda.jpg",
    password: "hashed_password_5",
    phone: "+1-555-0105",
    role: "candidate",
    city: "Boston",
    address: "202 Beacon St, Boston, MA 02116",
    skills: [
      "Machine Learning",
      "Python",
      "TensorFlow",
      "PyTorch",
      "Data Analysis",
    ],
    education: "PhD in Computer Science - Harvard University",
    yearsOfExperience: "8",
    github: "https://github.com/amandawatson",
    linkedin: "https://linkedin.com/in/amandawatson",
  },
  {
    _id: "cand-6",
    name: "James Anderson",
    slug: "james-anderson",
    email: "james.anderson@example.com",
    avatar: "/avatars/james.jpg",
    password: "hashed_password_6",
    phone: "+1-555-0106",
    role: "candidate",
    city: "Denver",
    address: "303 Colfax Ave, Denver, CO 80203",
    skills: ["Full Stack", "React", "Node.js", "MongoDB", "Express"],
    education: "Bachelor's in Computer Science - UC Berkeley",
    yearsOfExperience: "3",
    github: "https://github.com/jamesanderson",
    linkedin: "https://linkedin.com/in/jamesanderson",
  },
  {
    _id: "cand-7",
    name: "Lisa Patel",
    slug: "lisa-patel",
    email: "lisa.patel@example.com",
    avatar: "/avatars/lisa.jpg",
    password: "hashed_password_7",
    phone: "+1-555-0107",
    role: "candidate",
    city: "Los Angeles",
    address: "404 Sunset Blvd, Los Angeles, CA 90028",
    skills: ["Swift", "iOS", "SwiftUI", "UIKit", "Mobile Development"],
    education: "Bachelor's in Software Engineering - UCLA",
    yearsOfExperience: "5",
    github: "https://github.com/lisapatel",
    linkedin: "https://linkedin.com/in/lisapatel",
  },
  {
    _id: "cand-8",
    name: "Robert Taylor",
    slug: "robert-taylor",
    email: "robert.taylor@example.com",
    avatar: "/avatars/robert.jpg",
    password: "hashed_password_8",
    phone: "+1-555-0108",
    role: "candidate",
    city: "Chicago",
    address: "505 Michigan Ave, Chicago, IL 60611",
    skills: [
      "Digital Marketing",
      "SEO",
      "Content Strategy",
      "Analytics",
      "Social Media",
    ],
    education: "Bachelor's in Marketing - Northwestern University",
    yearsOfExperience: "4",
    linkedin: "https://linkedin.com/in/roberttaylor",
  },
];
