import { TNotification } from "@/types/collections";

export const dummyNotifications: TNotification[] = [
  {
    _id: "notif-1",
    userId: "cand-1",
    userType: "candidate",
    title: "New Job Match",
    message:
      "A new Senior Frontend Developer position at TechCorp Solutions matches your profile!",
    type: "job",
    isRead: false,
    relatedId: "1",
    createdAt: new Date("2025-11-22T10:00:00Z"),
  },
  {
    _id: "notif-2",
    userId: "cand-1",
    userType: "candidate",
    title: "Application Status Update",
    message:
      "Your application for Senior Frontend Developer has been shortlisted!",
    type: "application",
    isRead: true,
    relatedId: "1",
    createdAt: new Date("2025-11-20T14:30:00Z"),
  },
  {
    _id: "notif-3",
    userId: "comp-1",
    userType: "company",
    title: "New Application Received",
    message:
      "Sarah Johnson has applied for the Senior Frontend Developer position.",
    type: "application",
    isRead: false,
    relatedId: "1",
    createdAt: new Date("2025-11-21T09:15:00Z"),
  },
  {
    _id: "notif-4",
    userId: "cand-3",
    userType: "candidate",
    title: "New Review on Your Profile",
    message: "Design Studio Inc has left a review on your profile!",
    type: "review",
    isRead: false,
    relatedId: "rev-3",
    createdAt: new Date("2025-11-19T16:45:00Z"),
  },
  {
    _id: "notif-5",
    userId: "comp-2",
    userType: "company",
    title: "New Application Received",
    message: "Emily Rodriguez has applied for the Product Designer position.",
    type: "application",
    isRead: true,
    relatedId: "2",
    createdAt: new Date("2025-11-18T11:20:00Z"),
  },
  {
    _id: "notif-6",
    userId: "cand-5",
    userType: "candidate",
    title: "Job Recommendation",
    message:
      "Check out this Data Scientist position at AI Innovations Lab - it's perfect for you!",
    type: "job",
    isRead: false,
    relatedId: "4",
    createdAt: new Date("2025-11-23T08:00:00Z"),
  },
  {
    _id: "notif-7",
    userId: "cand-7",
    userType: "candidate",
    title: "Profile View Alert",
    message: "AppCraft Studios viewed your profile. Make sure it's up to date!",
    type: "general",
    isRead: true,
    relatedId: "comp-6",
    createdAt: new Date("2025-11-17T13:30:00Z"),
  },
  {
    _id: "notif-8",
    userId: "comp-4",
    userType: "company",
    title: "New Review Posted",
    message: "Dr. Amanda Watson has posted a review about AI Innovations Lab.",
    type: "review",
    isRead: false,
    relatedId: "rev-5",
    createdAt: new Date("2025-11-22T15:00:00Z"),
  },
  {
    _id: "notif-9",
    userId: "cand-6",
    userType: "candidate",
    title: "Application Deadline Reminder",
    message:
      "Don't forget! Your saved job 'Full Stack Developer' application deadline is in 5 days.",
    type: "general",
    isRead: false,
    relatedId: "8",
    createdAt: new Date("2025-11-23T09:00:00Z"),
  },
  {
    _id: "notif-10",
    userId: "comp-3",
    userType: "company",
    title: "Job Posting Expiring Soon",
    message:
      "Your Backend Engineer job posting will expire in 3 days. Consider renewing it.",
    type: "job",
    isRead: true,
    relatedId: "3",
    createdAt: new Date("2025-11-21T10:00:00Z"),
  },
];
