export interface Review {
  id: string;
  companyId: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  rating: number;
  position: string;
  workStatus: "Current Employee" | "Former Employee" | "Interviewed";
  reviewDate: string;
  title: string;
  pros: string;
  cons: string;
  helpful: number;
  verified: boolean;
}

export const dummyReviews: Review[] = [
  {
    id: "rev-1",
    companyId: "comp-1",
    userId: "user-1",
    userName: "Sarah Johnson",
    userAvatar: "/avatars/sarah.jpg",
    rating: 5,
    position: "Senior Frontend Developer",
    workStatus: "Current Employee",
    reviewDate: "2025-11-10T10:00:00Z",
    title: "Great company culture and amazing team",
    pros: "Excellent work-life balance, supportive management, cutting-edge technologies, great benefits package, and opportunities for growth.",
    cons: "Sometimes projects can be challenging with tight deadlines, but the team is always supportive.",
    helpful: 24,
    verified: true,
  },
  {
    id: "rev-2",
    companyId: "comp-1",
    userId: "user-2",
    userName: "Michael Chen",
    userAvatar: "/avatars/michael.jpg",
    rating: 4,
    position: "Backend Engineer",
    workStatus: "Current Employee",
    reviewDate: "2025-10-25T14:30:00Z",
    title: "Solid company with room for improvement",
    pros: "Good salary, interesting projects, smart colleagues, flexible remote work policy.",
    cons: "Communication between teams could be better. Sometimes unclear requirements.",
    helpful: 18,
    verified: true,
  },
  {
    id: "rev-3",
    companyId: "comp-2",
    userId: "user-3",
    userName: "Emily Rodriguez",
    userAvatar: "/avatars/emily.jpg",
    rating: 5,
    position: "Product Designer",
    workStatus: "Current Employee",
    reviewDate: "2025-11-05T09:15:00Z",
    title: "Dream job for designers",
    pros: "Creative freedom, supportive design team, latest tools and resources, amazing portfolio opportunities, clients across various industries.",
    cons: "Being a smaller company, sometimes resources are limited compared to larger agencies.",
    helpful: 31,
    verified: true,
  },
  {
    id: "rev-4",
    companyId: "comp-3",
    userId: "user-4",
    userName: "David Kim",
    userAvatar: "/avatars/david.jpg",
    rating: 4,
    position: "DevOps Engineer",
    workStatus: "Former Employee",
    reviewDate: "2025-09-20T11:00:00Z",
    title: "Great learning experience",
    pros: "Learned a lot about cloud infrastructure, good mentorship program, competitive salary.",
    cons: "Fast-paced environment can be stressful. On-site requirement was challenging for me.",
    helpful: 15,
    verified: true,
  },
  {
    id: "rev-5",
    companyId: "comp-4",
    userId: "user-5",
    userName: "Dr. Amanda Watson",
    userAvatar: "/avatars/amanda.jpg",
    rating: 5,
    position: "Senior Data Scientist",
    workStatus: "Current Employee",
    reviewDate: "2025-11-12T16:45:00Z",
    title: "Perfect for ML/AI researchers",
    pros: "Cutting-edge research, publication support, brilliant colleagues, access to best-in-class computing resources, conference opportunities.",
    cons: "High expectations, but that drives innovation.",
    helpful: 42,
    verified: true,
  },
  {
    id: "rev-6",
    companyId: "comp-5",
    userId: "user-6",
    userName: "James Anderson",
    userAvatar: "/avatars/james.jpg",
    rating: 4,
    position: "Site Reliability Engineer",
    workStatus: "Current Employee",
    reviewDate: "2025-10-30T13:20:00Z",
    title: "Solid DevOps company",
    pros: "Remote-first culture, good benefits, certification support, modern tech stack.",
    cons: "Smaller team means you wear many hats. Could use more process documentation.",
    helpful: 12,
    verified: true,
  },
  {
    id: "rev-7",
    companyId: "comp-6",
    userId: "user-7",
    userName: "Lisa Patel",
    userAvatar: "/avatars/lisa.jpg",
    rating: 5,
    position: "iOS Developer",
    workStatus: "Current Employee",
    reviewDate: "2025-11-08T10:30:00Z",
    title: "Best place for mobile developers",
    pros: "Latest Apple devices provided, focus on quality over quantity, great team culture, users love our apps.",
    cons: "Can't think of any major cons. Maybe more remote flexibility would be nice.",
    helpful: 28,
    verified: true,
  },
  {
    id: "rev-8",
    companyId: "comp-7",
    userId: "user-8",
    userName: "Robert Taylor",
    userAvatar: "/avatars/robert.jpg",
    rating: 4,
    position: "Marketing Specialist",
    workStatus: "Former Employee",
    reviewDate: "2025-09-15T15:00:00Z",
    title: "Great for learning digital marketing",
    pros: "Hands-on experience with various marketing channels, supportive team, data-driven approach.",
    cons: "Client demands can be high. Work-life balance varies by season.",
    helpful: 9,
    verified: true,
  },
  {
    id: "rev-9",
    companyId: "comp-8",
    userId: "user-9",
    userName: "Jennifer Lee",
    userAvatar: "/avatars/jennifer.jpg",
    rating: 5,
    position: "Full Stack Developer",
    workStatus: "Current Employee",
    reviewDate: "2025-11-15T12:00:00Z",
    title: "Startup energy with great potential",
    pros: "High impact work, equity package, rapid growth, wear multiple hats, direct access to founders.",
    cons: "Typical startup challenges - things change quickly, need to be comfortable with ambiguity.",
    helpful: 19,
    verified: true,
  },
  {
    id: "rev-10",
    companyId: "comp-1",
    userId: "user-10",
    userName: "Alex Martinez",
    rating: 4,
    position: "Software Engineer",
    workStatus: "Interviewed",
    reviewDate: "2025-11-01T14:00:00Z",
    title: "Positive interview experience",
    pros: "Well-organized interview process, friendly interviewers, clear communication about next steps.",
    cons: "Process took a bit longer than expected, but they kept me informed.",
    helpful: 7,
    verified: false,
  },
];
